// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tesli.Model.Sqlite;

namespace model.sqlite.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180819210335_AddLessonTables")]
    partial class AddLessonTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Tesli.Model.Entities.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("EndTime");

                    b.Property<string>("StartTime");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("Lesson");
                });

            modelBuilder.Entity("Tesli.Model.Entities.LessonAttendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("HasAttended");

                    b.Property<bool>("HasPaid");

                    b.Property<int>("LessonId");

                    b.Property<decimal>("Price");

                    b.Property<int>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("LessonAttendee");
                });

            modelBuilder.Entity("Tesli.Model.Entities.LessonRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EffectiveDate");

                    b.Property<int>("NumberOfStudents");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("LessonRates");
                });

            modelBuilder.Entity("Tesli.Model.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("ContactNumber");

                    b.Property<string>("Email");

                    b.Property<string>("Goals");

                    b.Property<byte?>("Grade");

                    b.Property<string>("Name");

                    b.Property<string>("ParentContactNumber");

                    b.Property<string>("ParentEmail");

                    b.Property<string>("ParentName");

                    b.Property<string>("School");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Tesli.Model.Entities.LessonAttendee", b =>
                {
                    b.HasOne("Tesli.Model.Entities.Lesson", "Lesson")
                        .WithMany("LessonAttendees")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tesli.Model.Entities.Student", "Student")
                        .WithMany("LessonAttendees")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
